### ISSUE TITLE
ServiceBusTriggeredEndpointConfiguration.Transport.UseWebSockets does not work.

### ISSUE THREAD

**Issue by JarkoDubbeldam** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#529]
See the following repos for a minimal example: https://github.com/JarkoDubbeldam/NServiceBus.Functions.WebSockets.Repro

When configuring an Azure Functions app with NServicebus-Azure Service Bus integration, the `UseWebSockets` configuration option to use HTTPS over port 443 instead of 5671 does not seem to work.

Using the following configuration:

```
    builder.UseNServiceBus(c => {
      var endpointConfiguration = new ServiceBusTriggeredEndpointConfiguration(EndpointName, c);
      endpointConfiguration.Transport.UseWebSockets();
      return endpointConfiguration;
    });
```
and `local.settings.json`:

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "AzureWebJobsServiceBus": <ASB-secret>
  }
}
```

When debugging the function locally from VS2022, with option `--verbose` I see the following (partial) output:
```
[2022-09-22T13:09:38.906Z] ServiceBusOptions
[2022-09-22T13:09:38.918Z] {
[2022-09-22T13:09:38.921Z]   "ClientRetryOptions": {
[2022-09-22T13:09:38.934Z]     "Mode": "Exponential",
[2022-09-22T13:09:38.938Z]     "TryTimeout": "00:01:00",
[2022-09-22T13:09:38.942Z]     "Delay": "00:00:00.8000000",
[2022-09-22T13:09:38.948Z]     "MaxDelay": "00:01:00",
[2022-09-22T13:09:38.953Z]     "MaxRetries": 3
[2022-09-22T13:09:38.956Z]   },
[2022-09-22T13:09:38.964Z]   "TransportType": "AmqpTcp",
[2022-09-22T13:09:38.968Z]   "WebProxy": "",
[2022-09-22T13:09:38.973Z]   "AutoCompleteMessages": true,
[2022-09-22T13:09:38.976Z]   "PrefetchCount": 0,
[2022-09-22T13:09:38.985Z]   "MaxAutoLockRenewalDuration": "00:05:00",
[2022-09-22T13:09:38.991Z]   "MaxConcurrentCalls": 128,
[2022-09-22T13:09:38.996Z]   "MaxConcurrentSessions": 8,
[2022-09-22T13:09:38.999Z]   "MaxMessageBatchSize": 1000,
[2022-09-22T13:09:39.011Z]   "SessionIdleTimeout": "",
[2022-09-22T13:09:39.015Z]   "EnableCrossEntityTransactions": false
[2022-09-22T13:09:39.019Z] }
```
Note that `TransportType` is still `AmqpTcp`. 

I'm not sure if I am doing something wrong, or if there is a bug. Can you help me?

**Comment by SeanFeldman** [comment]
@JarkoDubbeldam could you elaborate what's driving the need to use WebSockets with Azure Functions given there's no blocking of the port in Azure. Is that a local development issue by any chance? Are you creating your own senders (the repro doesn't show it)? Thanks.

**Comment by JarkoDubbeldam** [comment]
Mostly local development yeah. Firewalls block port 5671, but not 443.

**Comment by SeanFeldman** [comment]
Then how do you plan to receive messages using the ASB trigger if the TCP port is blocked?
Receiving is not done by NSB, but rather Functions SDK. And I don't think you can configure it to use WebSockets.

**Comment by JarkoDubbeldam** [comment]
From my earlier testing, it looked like adding `TransportType=AmqpWebSockets` would do the trick when using the Functions Messagebus trigger, but not when using NServicebus.

**Comment by SeanFeldman** [comment]
In your repro, I can't quite see where are you using NServiceBus. There are no handlers. Mind to update your repro to show exactly what's not working? Thanks.

**Comment by JarkoDubbeldam** [comment]
Even without any handlers, I'm getting a stream of exceptions:

```

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       4.0.4785 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.10.4.19213

[2022-09-23T06:22:44.910Z] Found C:\Users\jdubbeldam\source\repos\MinimalRepro\MinimalRepro\MinimalRepro.csproj. Using for user secrets file configuration.
[2022-09-23T06:22:46.723Z] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '82611b3a-dd01-4d38-baa1-0ef554ccaa8a'
[2022-09-23T06:22:46.738Z] Reading host configuration file 'C:\Users\jdubbeldam\source\repos\MinimalRepro\MinimalRepro\bin\Debug\net6.0\host.json'
[2022-09-23T06:22:46.742Z] Host configuration file read:
[2022-09-23T06:22:46.745Z] {
[2022-09-23T06:22:46.748Z]   "version": "2.0",
[2022-09-23T06:22:46.751Z]   "logging": {
[2022-09-23T06:22:46.753Z]     "applicationInsights": {
[2022-09-23T06:22:46.756Z]       "samplingSettings": {
[2022-09-23T06:22:46.759Z]         "isEnabled": true,
[2022-09-23T06:22:46.762Z]         "excludedTypes": "Request"
[2022-09-23T06:22:46.764Z]       }
[2022-09-23T06:22:46.767Z]     }
[2022-09-23T06:22:46.770Z]   }
[2022-09-23T06:22:46.772Z] }
[2022-09-23T06:22:46.800Z] Loading extensions from C:\Users\jdubbeldam\source\repos\MinimalRepro\MinimalRepro\bin\Debug\net6.0\bin. BundleConfigured: False, PrecompiledFunctionApp: False, LegacyBundle: False
[2022-09-23T06:22:46.804Z] Script Startup resetting load context with base path: 'C:\Users\jdubbeldam\source\repos\MinimalRepro\MinimalRepro\bin\Debug\net6.0\bin'.
[2022-09-23T06:22:46.820Z] Loading startup extension 'ServiceBus'
[2022-09-23T06:22:46.986Z] Loaded extension 'ServiceBus' (5.2.0.0)
[2022-09-23T06:22:47.007Z] Loading startup extension 'ServiceBus'
[2022-09-23T06:22:47.023Z] Loaded extension 'ServiceBus' (4.3.0.0)
[2022-09-23T06:22:47.026Z] Loading startup extension 'Startup'
[2022-09-23T06:22:47.053Z] Loaded extension 'Startup' (1.0.0.0)
[2022-09-23T06:22:47.089Z] Reading host configuration file 'C:\Users\jdubbeldam\source\repos\MinimalRepro\MinimalRepro\bin\Debug\net6.0\host.json'
[2022-09-23T06:22:47.092Z] Host configuration file read:
[2022-09-23T06:22:47.095Z] {
[2022-09-23T06:22:47.098Z]   "version": "2.0",
[2022-09-23T06:22:47.101Z]   "logging": {
[2022-09-23T06:22:47.104Z]     "applicationInsights": {
[2022-09-23T06:22:47.107Z]       "samplingSettings": {
[2022-09-23T06:22:47.110Z]         "isEnabled": true,
[2022-09-23T06:22:47.112Z]         "excludedTypes": "Request"
[2022-09-23T06:22:47.115Z]       }
[2022-09-23T06:22:47.119Z]     }
[2022-09-23T06:22:47.121Z]   }
[2022-09-23T06:22:47.124Z] }
[2022-09-23T06:22:55.612Z] Initializing Warmup Extension.
[2022-09-23T06:22:55.695Z] Initializing Host. OperationId: '82611b3a-dd01-4d38-baa1-0ef554ccaa8a'.
[2022-09-23T06:22:55.712Z] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=82611b3a-dd01-4d38-baa1-0ef554ccaa8a
[2022-09-23T06:22:55.764Z] Loading functions metadata
[2022-09-23T06:22:55.773Z] Reading functions metadata
[2022-09-23T06:22:55.779Z] Reading functions metadata
[2022-09-23T06:22:55.797Z] 1 functions found
[2022-09-23T06:22:55.800Z] 1 functions found
[2022-09-23T06:22:55.812Z] 1 functions loaded
[2022-09-23T06:22:55.825Z] LoggerFilterOptions
[2022-09-23T06:22:55.828Z] {
[2022-09-23T06:22:55.831Z]   "MinLevel": "None",
[2022-09-23T06:22:55.833Z]   "Rules": [
[2022-09-23T06:22:55.836Z]     {
[2022-09-23T06:22:55.839Z]       "ProviderName": null,
[2022-09-23T06:22:55.841Z]       "CategoryName": null,
[2022-09-23T06:22:55.844Z]       "LogLevel": null,
[2022-09-23T06:22:55.859Z]       "Filter": "<AddFilter>b__0"
[2022-09-23T06:22:55.862Z]     },
[2022-09-23T06:22:55.867Z]     {
[2022-09-23T06:22:55.872Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2022-09-23T06:22:55.876Z]       "CategoryName": null,
[2022-09-23T06:22:55.883Z]       "LogLevel": "None",
[2022-09-23T06:22:55.886Z]       "Filter": null
[2022-09-23T06:22:55.901Z]     },
[2022-09-23T06:22:55.904Z]     {
[2022-09-23T06:22:55.910Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2022-09-23T06:22:55.913Z]       "CategoryName": null,
[2022-09-23T06:22:55.923Z]       "LogLevel": null,
[2022-09-23T06:22:55.927Z]       "Filter": "<AddFilter>b__0"
[2022-09-23T06:22:55.930Z]     },
[2022-09-23T06:22:55.937Z]     {
[2022-09-23T06:22:55.947Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2022-09-23T06:22:55.951Z]       "CategoryName": null,
[2022-09-23T06:22:55.954Z]       "LogLevel": null,
[2022-09-23T06:22:55.963Z]       "Filter": "<AddFilter>b__0"
[2022-09-23T06:22:55.966Z]     }
[2022-09-23T06:22:55.973Z]   ]
[2022-09-23T06:22:55.986Z] }
[2022-09-23T06:22:55.989Z] LoggerFilterOptions
[2022-09-23T06:22:56.001Z] {
[2022-09-23T06:22:56.013Z]   "MinLevel": "None",
[2022-09-23T06:22:56.019Z]   "Rules": [
[2022-09-23T06:22:56.026Z]     {
[2022-09-23T06:22:56.032Z]       "ProviderName": null,
[2022-09-23T06:22:56.038Z]       "CategoryName": null,
[2022-09-23T06:22:56.041Z]       "LogLevel": null,
[2022-09-23T06:22:56.057Z]       "Filter": "<AddFilter>b__0"
[2022-09-23T06:22:56.060Z]     },
[2022-09-23T06:22:56.066Z]     {
[2022-09-23T06:22:56.074Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2022-09-23T06:22:56.081Z]       "CategoryName": null,
[2022-09-23T06:22:56.085Z]       "LogLevel": "None",
[2022-09-23T06:22:56.091Z]       "Filter": null
[2022-09-23T06:22:56.094Z]     },
[2022-09-23T06:22:56.106Z]     {
[2022-09-23T06:22:56.109Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2022-09-23T06:22:56.115Z]       "CategoryName": null,
[2022-09-23T06:22:56.126Z]       "LogLevel": null,
[2022-09-23T06:22:56.139Z]       "Filter": "<AddFilter>b__0"
[2022-09-23T06:22:56.142Z]     },
[2022-09-23T06:22:56.146Z]     {
[2022-09-23T06:22:56.153Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2022-09-23T06:22:56.156Z]       "CategoryName": null,
[2022-09-23T06:22:56.171Z]       "LogLevel": null,
[2022-09-23T06:22:56.175Z]       "Filter": "<AddFilter>b__0"
[2022-09-23T06:22:56.183Z]     }
[2022-09-23T06:22:56.186Z]   ]
[2022-09-23T06:22:56.190Z] }
[2022-09-23T06:22:56.197Z] ConcurrencyOptions
[2022-09-23T06:22:56.214Z] {
[2022-09-23T06:22:56.218Z]   "DynamicConcurrencyEnabled": false,
[2022-09-23T06:22:56.224Z]   "MaximumFunctionConcurrency": 500,
[2022-09-23T06:22:56.236Z]   "CPUThreshold": 0.8,
[2022-09-23T06:22:56.251Z]   "SnapshotPersistenceEnabled": true
[2022-09-23T06:22:56.261Z] }
[2022-09-23T06:22:56.265Z] FunctionResultAggregatorOptions
[2022-09-23T06:22:56.271Z] {
[2022-09-23T06:22:56.284Z]   "BatchSize": 1000,
[2022-09-23T06:22:56.287Z]   "FlushTimeout": "00:00:30",
[2022-09-23T06:22:56.295Z]   "IsEnabled": true
[2022-09-23T06:22:56.298Z] }
[2022-09-23T06:22:56.307Z] SingletonOptions
[2022-09-23T06:22:56.314Z] {
[2022-09-23T06:22:56.317Z]   "LockPeriod": "00:00:15",
[2022-09-23T06:22:56.325Z]   "ListenerLockPeriod": "00:00:15",
[2022-09-23T06:22:56.329Z]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[2022-09-23T06:22:56.332Z]   "LockAcquisitionPollingInterval": "00:00:05",
[2022-09-23T06:22:56.343Z]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[2022-09-23T06:22:56.348Z] }
[2022-09-23T06:22:56.353Z] ServiceBusOptions
[2022-09-23T06:22:56.360Z] {
[2022-09-23T06:22:56.364Z]   "ClientRetryOptions": {
[2022-09-23T06:22:56.371Z]     "Mode": "Exponential",
[2022-09-23T06:22:56.374Z]     "TryTimeout": "00:01:00",
[2022-09-23T06:22:56.385Z]     "Delay": "00:00:00.8000000",
[2022-09-23T06:22:56.388Z]     "MaxDelay": "00:01:00",
[2022-09-23T06:22:56.395Z]     "MaxRetries": 3
[2022-09-23T06:22:56.408Z]   },
[2022-09-23T06:22:56.422Z]   "TransportType": "AmqpTcp",
[2022-09-23T06:22:56.430Z]   "WebProxy": "",
[2022-09-23T06:22:56.433Z]   "AutoCompleteMessages": true,
[2022-09-23T06:22:56.453Z]   "PrefetchCount": 0,
[2022-09-23T06:22:56.456Z]   "MaxAutoLockRenewalDuration": "00:05:00",
[2022-09-23T06:22:56.463Z]   "MaxConcurrentCalls": 128,
[2022-09-23T06:22:56.467Z]   "MaxConcurrentSessions": 8,
[2022-09-23T06:22:56.473Z]   "MaxMessageBatchSize": 1000,
[2022-09-23T06:22:56.485Z]   "SessionIdleTimeout": "",
[2022-09-23T06:22:56.488Z]   "EnableCrossEntityTransactions": false
[2022-09-23T06:22:56.491Z] }
[2022-09-23T06:22:56.503Z] Starting JobHost
[2022-09-23T06:22:56.520Z] Starting Host (HostId=sdatsc02-1732979031, InstanceId=26914d6b-d789-4be7-a2db-7d78e7c2e351, Version=4.10.4.19213, ProcessId=26080, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[2022-09-23T06:22:56.556Z] Loading functions metadata
[2022-09-23T06:22:56.559Z] Reading functions metadata
[2022-09-23T06:22:56.563Z] Reading functions metadata
[2022-09-23T06:22:56.574Z] 1 functions found
[2022-09-23T06:22:56.578Z] 1 functions found
[2022-09-23T06:22:56.603Z] 1 functions loaded
[2022-09-23T06:22:56.753Z] Generating 1 job function(s)
[2022-09-23T06:22:56.842Z] Found the following functions:
[2022-09-23T06:22:56.849Z] FunctionEndpointTrigger.Run
[2022-09-23T06:22:56.855Z]
[2022-09-23T06:22:56.867Z] The 'AutoCompleteMessages' option has been overriden to 'True' value for 'NServiceBusFunctionEndpointTrigger-MyEndpoint' function.
[2022-09-23T06:22:56.883Z] HttpOptions
[2022-09-23T06:22:56.887Z] {
[2022-09-23T06:22:56.890Z]   "DynamicThrottlesEnabled": false,
[2022-09-23T06:22:56.897Z]   "EnableChunkedRequestBinding": false,
[2022-09-23T06:22:56.908Z]   "MaxConcurrentRequests": -1,
[2022-09-23T06:22:56.921Z]   "MaxOutstandingRequests": -1,
[2022-09-23T06:22:56.925Z]   "RoutePrefix": "api"
[2022-09-23T06:22:56.940Z] }
[2022-09-23T06:22:56.886Z] Initializing function HTTP routes
[2022-09-23T06:22:56.952Z] No HTTP routes mapped
[2022-09-23T06:22:56.962Z]
[2022-09-23T06:22:56.982Z] Host initialized (435ms)
[2022-09-23T06:22:57.515Z] Host started (983ms)
[2022-09-23T06:22:57.519Z] Job host started

Functions:

        NServiceBusFunctionEndpointTrigger-MyEndpoint: serviceBusTrigger

[2022-09-23T06:23:01.578Z] Host lock lease acquired by instance ID '0000000000000000000000008100B5AD'.
[2022-09-23T06:24:32.922Z] Message processing error (Action=Receive, EntityPath=MyEndpoint, Endpoint=<redacted>.servicebus.windows.net)
[2022-09-23T06:24:32.925Z] System.Private.CoreLib: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem). System.Private.CoreLib: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2022-09-23T06:24:32.922Z] Message processing error (Action=Receive, EntityPath=MyEndpoint, Endpoint=<redacted>.servicebus.windows.net)
[2022-09-23T06:24:32.922Z] Message processing error (Action=Receive, EntityPath=MyEndpoint, Endpoint=<redacted>.servicebus.windows.net)
[2022-09-23T06:24:32.939Z] System.Private.CoreLib: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem). System.Private.CoreLib: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2022-09-23T06:24:32.922Z] Message processing error (Action=Receive, EntityPath=MyEndpoint, Endpoint=<redacted>.servicebus.windows.net)
[2022-09-23T06:24:32.922Z] Message processing error (Action=Receive, EntityPath=MyEndpoint, Endpoint=<redacted>.servicebus.windows.net)
[2022-09-23T06:24:32.960Z] System.Private.CoreLib: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem). System.Private.CoreLib: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2022-09-23T06:24:32.922Z] Message processing error (Action=Receive, EntityPath=MyEndpoint, Endpoint=<redacted>.servicebus.windows.net)
     Repeating on and on from here.
```

**Comment by JarkoDubbeldam** [comment]
If I edit the loglevel in host.json, this is the stacktrace:

```
[2022-09-23T06:28:53.302Z] An exception occurred while creating receive link for Identifier: MyEndpoint-a5b70c62-5b41-48d4-a5b9-40604f38e0ed. Error Message: 'System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2022-09-23T06:28:53.307Z]    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
[2022-09-23T06:28:53.325Z]    at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
[2022-09-23T06:28:53.332Z]    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[2022-09-23T06:28:53.337Z] --- End of stack trace from previous location ---
[2022-09-23T06:28:53.343Z]    at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, ServiceBusTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)
[2022-09-23T06:28:53.379Z]    at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
[2022-09-23T06:28:53.383Z]    at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
[2022-09-23T06:28:53.386Z]    at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
[2022-09-23T06:28:53.393Z]    at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)
[2022-09-23T06:28:53.398Z]    at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)'
[2022-09-23T06:28:53.475Z] RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem)
[2022-09-23T06:28:53.487Z]  ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2022-09-23T06:28:53.495Z]    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
[2022-09-23T06:28:53.475Z] RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem)[2022-09-23T06:28:53.475Z] RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem)
[2022-09-23T06:28:53.475Z] RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem)
[2022-09-23T06:28:53.475Z] RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem)
[2022-09-23T06:28:53.475Z] RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem)
[2022-09-23T06:28:53.564Z]  ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2022-09-23T06:28:53.475Z] RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem)
[2022-09-23T06:28:53.587Z]  ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2022-09-23T06:28:53.475Z] RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut (ServiceCommunicationProblem)
[2022-09-23T06:28:53.613Z]  ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2022-09-23T06:28:53.620Z]    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
[2022-09-23T06:28:53.633Z]    at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
[2022-09-23T06:28:53.636Z]    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[2022-09-23T06:28:53.650Z] --- End of stack trace from previous location ---
[2022-09-23T06:28:53.503Z]    at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
[2022-09-23T06:28:53.673Z]    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[2022-09-23T06:28:53.682Z] --- End of stack trace from previous location ---
[2022-09-23T06:28:53.691Z]    at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, ServiceBusTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)
[2022-09-23T06:28:53.695Z]    at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
[2022-09-23T06:28:53.711Z]    at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
[2022-09-23T06:28:53.715Z]    at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
[2022-09-23T06:28:53.538Z]  ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2022-09-23T06:28:53.727Z]    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
[2022-09-23T06:28:53.730Z]    at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
[2022-09-23T06:28:53.582Z]    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
[2022-09-23T06:28:53.761Z]    at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
[2022-09-23T06:28:53.772Z]    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

**Comment by SeanFeldman** [comment]
Maybe I'm missing something but the failing receiving operation is not NSB operation.
If you remove NServiceBus and have a plain ASB trigger, would it work?

**Comment by JarkoDubbeldam** [comment]
I updated the repro repos. One project where I just use the Functions SDK to connect to the servicebus, one (the original) with NServicebus. 

Both use the same connectionstring:

```
Endpoint=sb://<redacted>.servicebus.windows.net/;SharedAccessKeyName=<redacted>;SharedAccessKey=<redacted>;TransportType=AmqpWebSockets
```

In the vanilla Functions SDK version, it succesfully handles messages, but not so in the NServicebus version. It seems to me like the functionality to use websockets exists within the SDK, but somehow doesn't get configured correctly when using NServicebus API.

**Comment by JarkoDubbeldam** [comment]
Ah. I think I found a discrepancy between my two versions:

When creating a Functions app in VS with ServiceBus trigger, the default reference is `Microsoft.Azure.WebJobs.Extensions.ServiceBus` version `4.3.0`. The version of the `NServiceBus.AzureFunctions.InProcess.ServiceBus` that I used (`3.0.0`) requires `Microsoft.Azure.WebJobs.Extensions.ServiceBus>=5.2.0`. If I use that version in my SDK version, it breaks as well. So this seems to be a breaking change in the Microsoft SDK after all.

**Comment by SeanFeldman** [comment]
When providing `SendsAtomicWithReceive = true` (atomic processing), the same ASB client used by Functions will be used by NSB.
If you update your function to [assembly: `NServiceBusTriggerFunction(Startup.EndpointName, SendsAtomicWithReceive = true)]` will it throw as well or not?

**Comment by SeanFeldman** [comment]
SDK discrepancies would do it.

**Comment by JarkoDubbeldam** [comment]
I downgraded to NServicebus 2.1.0, which references the Microsoft 4.3.0 package. SendsAtomicWithReceive doesn't seem to change anything, but creating a CustomTrigger (following [this](https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/custom-triggers?version=asbfunctions_2.0)) does work.

**Comment by JarkoDubbeldam** [comment]
It seems that this is a sort-of workaround, although it appears that the SendsAtomicWithReceive option is broken in the downgraded package (#392). For simple local development this might be somewhat acceptable.

For the rest, the root issue looks to be in the Microsoft package, so I'll take this there. 

Thanks for the help.

**Comment by JarkoDubbeldam** [comment]
For future reference: https://github.com/Azure/azure-sdk-for-net/issues/31389#issuecomment-1256257327
